#!/usr/bin/env bash
# This Bash script configures a new Ubuntu machine to match the task requirements

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure web-01 server
echo 'Hello web-01!' | sudo tee /var/www/html/index.html
echo 'server { add_header X-Served-By "web-01"; }' | sudo tee /etc/nginx/sites-available/web-01
ln -sf /etc/nginx/sites-available/web-01 /etc/nginx/sites-enabled/

# Configure web-02 server
echo 'Hello web-02!' | sudo tee /var/www/html/index.html
echo 'server { add_header X-Served-By "web-02"; }' | sudo tee /etc/nginx/sites-available/web-02
ln -sf /etc/nginx/sites-available/web-02 /etc/nginx/sites-enabled/

# Restart Nginx
systemctl restart nginx

